name: 'Continuous Delivery'

on:
  workflow_run:
    workflows: ["CI - Integración Continua en Windows"]
    types:
      - completed

jobs:

  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: my-project-2023-398103

      - name: Construir y etiquetar imagen de Docker
        run: |
          docker build -t api-latam:v1 C:\Users\Valeria\Documents\Cursos_Programación\latam-challenge
          docker tag api-latam:v1 southamerica-west1-docker.pkg.dev/my-project-2023-398103/registro-1/api-latam:v1

      - name: Iniciar sesión en Docker Registry de GCP
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://southamerica-west1-docker.pkg.dev

      - name: Subir imagen de Docker a Docker Registry de GCP
        run: |
          docker push southamerica-west1-docker.pkg.dev/my-project-2023-398103/registro-1/api-latam:v1

      - name: Desplegar en GCP App Engine
        run: |
          # Configura el entorno de Google Cloud
          gcloud auth activate-service-account --key-file=google-cloud-service-key.json
          gcloud config set project my-project-2023-398103

          # Despliega la API en App Engine de GCP utilizando la imagen de Docker subida
          gcloud app deploy --image-url=southamerica-west1-docker.pkg.dev/my-project-2023-398103/registro-1/api-latam:v1

      - name: Ejecutar Test de Estrés
        run: |
          # Ejecutar el test de estrés utilizando el comando: make stress-test desde la ubicación del Makefile